parameters:
#    cituao_academico.example.class: Cituao\AcademicoBundle\Example

services:
#    cituao_academico.example:
#        class: %cituao_academico.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
