cituao_externo_homepage:
    pattern:  /externo
    defaults: { _controller: CituaoExternoBundle:Default:index }

cituao_externo_practicantes:
    path:  /externo/practicantes
    defaults: { _controller: CituaoExternoBundle:Default:practicantes }

cituao_externo_cronograma:
    path:  /externo/cronograma/{id}
    defaults: { _controller: CituaoExternoBundle:Default:cronograma }

cituao_externo_registrar_evaluacion:
    path:  /externo/registrarcomentario/practicante={id}&evaluacion={numeva}
    defaults: { _controller: CituaoExternoBundle:Default:registrarEvaluacion }

cituao_externo_registrar_conformidad:
    path:  /externo/registrarconformidad/practicante={id}
    defaults: { _controller: CituaoExternoBundle:Default:registrarConformidad }

cituao_externo_actualizar:
    path:  /externo/mis-datos
    defaults: { _controller: CituaoExternoBundle:Default:actualizar }

cituao_externo_verasesoracademico:
    path:  /externo/asesoracademico/academico={id}
    defaults: { _controller: CituaoExternoBundle:Default:verasesorAcademico }

cituao_externo_registrar_acta:
    path:  /externo/registrar-acta/practicante={id}
    defaults: { _controller: CituaoExternoBundle:Default:registrarconformidad }