parameters:
#    cituao_externo.example.class: Cituao\ExternoBundle\Example

services:
#    cituao_externo.example:
#        class: %cituao_externo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
