Cituao\ExternoBundle\Entity\Externo:
properties:
ci:
- NotBlank: ~
nombres:
- NotBlank: ~
apellidos:
- NotBlank: ~
telefonoMovil:
- NotBlank: ~
telefonoFijo:
- NotBlank: ~
email:
- Email
message: El correo no es válido
checkMX: true
cargo:
- NotBlank