cituao_academico:
    resource: "@CituaoAcademicoBundle/Resources/config/routing.yml"
    prefix:   /

cituao_externo:
    resource: "@CituaoExternoBundle/Resources/config/routing.yml"
    prefix:   /

cituao_practicante:
    resource: "@CituaoPracticanteBundle/Resources/config/routing.yml"
    prefix:   /

cituao_coord:
    resource: "@CituaoCoordBundle/Resources/config/routing.yml"
    prefix:   /

cituao_usuario:
    resource: "@CituaoUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

cituao_portal:
    resource: "@CituaoPortalBundle/Resources/config/routing.yml"
    prefix:   /
