# app/config/security.yml
security:

    role_hierarchy:
        ROLE_COORDINADOR:       ROLE_USER
        ROLE_PRACTICANTE:       ROLE_USER
        ROLE_ADMIN: [ROLE_COORDINADOR, ROLE_PRACTICANTE]

    firewalls:
        secured_area:
            pattern:   ^/*
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path:       usuario_logout
            
            provider:       in_memory 

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coordinador/*, roles: ROLE_COORDINADOR }
        - { path: ^/practicante/*, roles: ROLE_PRACTICANTE }

    providers:
        in_memory:
            memory:
                users:
                    coordinador:  { password: 1234, roles: 'ROLE_COORDINADOR' }
                    admin: { password: 12, roles: 'ROLE_ADMIN' }
                    1113036709: { password: 1234, roles: 'ROLE_PRACTICANTE' }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cituao\UsuarioBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
