security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Cituao\UsuarioBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1


    role_hierarchy:
        ROLE_COORDINA:     ROLE_USER
        ROLE_ADMIN:        ROLE_COORDINA
        

    firewalls:

        secured_area:
            pattern:    ^/
            form_login:
                check_path: usuario_login_check
                login_path: usuario_login
                #success_handler: login_listener
                
  
            anonymous: true
            provider:       usuarios
            
            logout:
                path:       usuario_logout

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coordinador/*,        roles: ROLE_ADMIN }
        - { path: ^/practicante/*,         roles: ROLE_PRACTICANTE }
        - { path: ^/asesora/*,         roles: ROLE_ASESORA }
        - { path: ^/asesore/*,         roles: ROLE_ASESORE }
      
    providers:
        usuarios:
           entity: {class: Cituao\UsuarioBundle\Entity\Usuario, property: username }                  
 

