security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        #Cituao\UsuarioBundle\Entity\Usuario:
        #    algorithm:        sha1
        #    encode_as_base64: false
        #    iterations:       1


    role_hierarchy:
        ROLE_PRACTICANTE: ROLE_USER
        ROLE_ASESORA:     ROLE_USER
        ROLE_ASESORE:     ROLE_USER
        ROLE_ADMIN:       [ROLE_PRACTICANTE, ROLE_ASESORA, ROLE_ASESORE, ROLE_PRACTICANTE]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #administrators:
        #   entity: { class: CituaoUsuarioBundle:Usuario }

        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: admin, roles: 'ROLE_ADMIN' }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: usuario_login_check
                login_path: usuario_login
            logout:
                path:   /logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/coordinador/*,        roles: ROLE_COORDINADOR }
        - { path: ^/practicante/*,         roles: ROLE_PRACTICANTE }
        - { path: ^/asesora/*,         roles: ROLE_ASESORA }
        - { path: ^/asesore/*,         roles: ROLE_ASESORE }


