security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Cituao\UsuarioBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1


    role_hierarchy:
        ROLE_PRACTICANTE: ROLE_USER
        ROLE_ASESORA:     ROLE_USER
        ROLE_ASESORE:     ROLE_USER
        ROLE_ADMIN:       [ROLE_PRACTICANTE, ROLE_ASESORA, ROLE_ASESORE, ROLE_PRACTICANTE]
        
    providers:
        administrators:
           entity: {class: Cituao\UsuarioBundle\Entity\Usuario, property: username }                  
 
    firewalls:

        secured_area:
            pattern:    ^/
            form_login:
                check_path: usuario_login_check
                login_path: usuario_login
                #success_handler: access_listener
                
            logout:
                path:   /logout
                target: /
            anonymous: true
            provider:       administrators
            


    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coordinador/*,        roles: ROLE_ADMIN }
        - { path: ^/practicante/*,         roles: ROLE_PRACTICANTE }
        - { path: ^/asesora/*,         roles: ROLE_ASESORA }
        - { path: ^/asesore/*,         roles: ROLE_ASESORE }
      


