# app/config/security.yml
security:

    role_hierarchy:
        ROLE_COORDINADOR:       ROLE_USER
        ROLE_PRACTICANTE:       ROLE_USER
        ROLE_ADMIN: [ROLE_COORDINADOR, ROLE_PRACTICANTE]

    firewalls:
        secured_area:
            pattern:   ^/*
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path:       /logout
            
            provider:       usuarios

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coordinador/*, roles: ROLE_COORDINADOR }
        - { path: ^/practicante/*, roles: ROLE_PRACTICANTE }
        - { path: ^/externo/*, roles: ROLE_ASESOR_EXT } 
        - { path: ^/academico/*, roles: ROLE_ASESOR_ACA } 

    providers:
        usuarios:
            entity: { class: Cituao\UsuarioBundle\Entity\Usuario, property: username }

    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        Cituao\UsuarioBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
