# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:   ^/*
            anonymous: ~
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
                csrf_provider: form.csrf_provider
            logout:
                path:       /logout
            
            provider:       chain_provider

    access_control:
        - { path: ^/adm, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/coordinador/*, roles: ROLE_COORDINADOR }
        - { path: ^/practicante/*, roles: ROLE_PRACTICANTE }
        - { path: ^/externo/*, roles: ROLE_ASESOR_EXT } 
        - { path: ^/academico/*, roles: ROLE_ASESOR_ACA } 

    providers:
        chain_provider:
            chain:
                    providers: [in_memory, usuarios]
        in_memory:
             memory:
                    users:
                          AdmUAO: { password: d0be2dc421be4fcd0172e5afceea3970e2f3d940, roles: 'ROLE_ADMIN' }
        usuarios:
            entity: { class: Cituao\UsuarioBundle\Entity\Usuario, property: username }

    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: sha1
            encode_as_base64: false
            iterations:         1

        Cituao\UsuarioBundle\Entity\Usuario:
            algorithm:        sha1
            encode_as_base64: false
            iterations:         1