cituao_portal_homepage:
    pattern:  /
    defaults: { _controller: CituaoPortalBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: CituaoPortalBundle:Default:login }

login_check:
    path: /login_check

cituao_portal_uao:
    pattern:  /
    defaults: { _controller: CituaoPortalBundle:Default:palla }
