Cituao\AcademicoBundle\Entity\Academico:
    type: entity
    repositoryClass: Cituao\AcademicoBundle\Entity\AcademicoRepository
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombres:
            type: string
            length: '50'
        apellidos:
            type: string
            length: '50'
        ci:
            type: string
            length: '12'
        telefonoMovil:
            type: string
            length: '15'
            nullable: true
        telefonoFijo:
            type: string
            length: '15'
            nullable: true
        email:
            type: string
            length: '50'
            nullable: true
        emailInstitucional:
            type: string
            length: '50'
            nullable: true
        perfil:
            type: text
            length: '500'
            nullable: true
        categoria:
            type: string
            length: '1'
            nullable: true
        declaracion:
            type: boolean
            nullable: true
        path:
            type: string
            length: '30'
            nullable: true
    oneToMany:
        practicantes:
            targetEntity: Cituao\CoordBundle\Entity\Practicante
            mappedBy: academico
    manyToOne:
        programa:
            targetEntity: Cituao\UsuarioBundle\Entity\Programa
            inversedBy: academicos
            joinColumn:
                name: programa
                referencedColumnName: id
    lifecycleCallbacks: {  }
