Cituao\AcademicoBundle\Entity\Academico:
    type: entity
    repositoryClass: Cituao\AcademicoBundle\Entity\AcademicoRepository
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombres:
            type: string
            length: '50'
        apellidos:
            type: string
            length: '50'
        ci:
            type: string
            length: '12'
        telefonoMovil:
            type: string
            length: '15'
            nullable: true
        telefonoFijo:
            type: string
            length: '15'
            nullable: true
        email:
            type: string
            length: '50'
            nullable: true
        perfil:
            type: text
            length: '500'
            nullable: true
        categoria:
            type: string
            length: '1'
            nullable: true
        declaracion:
            type: boolean
            nullable: true
        fechaAsesoria1:
            type: date
            nullable: true
        fechaAsesoria2:
            type: date
            nullable: true
        fechaAsesoria3:
            type: date
            nullable: true
        fechaAsesoria4:
            type: date
            nullable: true
        fechaAsesoria5:
            type: date
            nullable: true
        fechaAsesoria6:
            type: date
            nullable: true
        fechaAsesoria7:
            type: date
            nullable: true
        fechaVisitaP:
            type: date
            nullable: true
        fechaVisita1:
            type: date
            nullable: true
        fechaVisita2:
            type: date
            nullable: true
        fechaInformeGestion1:
            type: date
            nullable: true
            default: 0
        fechaInformeGestion2:
            type: date
            nullable: true
            default: 0
        fechaInformeGestion3:
            type: date
            nullable: true
            default: 0
        fechaEvaluacionFinal:
            type: date
            nullable: true
            default: 0
        listoAsesoria1:
            type: boolean
            nullable: true
            default: 0
        listoAsesoria2:
            type: boolean
            nullable: true
            default: 0
        listoAsesoria3:
            type: boolean
            nullable: true
            default: 0
        listoAsesoria4:
            type: boolean
            nullable: true
            default: 0
        listoAsesoria5:
            type: boolean
            nullable: true
            default: 0
        listoAsesoria6:
            type: boolean
            nullable: true
            default: 0
        listoAsesoria7:
            type: boolean
            nullable: true
            default: 0
        listoVisitaP:
            type: boolean
            nullable: true
            default: 0
        listoVisita1:
            type: boolean
            nullable: true
            default: 0
        listoVisita2:
            type: boolean
            nullable: true
            default: 0
        listoInformeGestion1:
            type: boolean
            nullable: true
            default: 0
        listoInformeGestion2:
            type: boolean
            nullable: true
            default: 0
        listoInformeGestion3:
            type: boolean
            nullable: true
            default: 0
        listoEvaluacionFinal:
            type: boolean
            nullable: true
            default: 0
        path:
            type: string
            length: '30'
            nullable: true
    oneToMany:
        practicantes:
            targetEntity: Cituao\CoordBundle\Entity\Practicante
            mappedBy: academico
    lifecycleCallbacks: {  }
