Cituao\CoordBundle\Entity\Area:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        area:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
