Cituao\CoordBundle\Entity\Asesoria4:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        practicante:
            type: integer
            unique: true
        academico:
            type: integer
        docAsesor4:
            type: text
            nullable: true
        docPracticante4:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
