# Ruta para la acción de login de de los usuarios del frontend
usuario_login:
    pattern:   /login
    defaults:  { _controller: CituaoUsuarioBundle:Default:login }

# Ruta para la acción que comprueba el login del frontend
usuario_login_check:
    pattern:   /login_check

# Ruta para el registro de usuarios
usuario_registro:
    pattern: /coordinador/registrar
    defaults:  { _controller: CituaoUsuarioBundle:Default:registro }

# Ruta para la acción de logout de los usuarios del frontend extranet
usuario_logout:
    pattern:   /logout

# Ruta para el homepage del administrador
usuario_adm_homepage:
    pattern:   /adm
    defaults:  { _controller: CituaoUsuarioBundle:Default:adm }

# Ruta para confguracion del sistema
usuario_adm_configuracion:
    pattern:  /adm/configuracion
    defaults:  {_controller: CituaoUsuarioBundle:Default:configuracion }    
