parameters:
#    cituao_usuario.example.class: Cituao\UsuarioBundle\Example
#scope: request
services:
#    cituao_usuario.example:
#        class: %cituao_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
#services:
#  access_listener:
#    class: Cituao\UsuarioBundle\Listener\SecurityListener
#    scope: container
#    arguments: [@security.context, @router]
#    tags:
#           - { name: kernel.event_listener, event: security.interactive_login }
#           - { name: kernel.event_listener, event: kernel.response }
