parameters:
#    cituao_usuario.example.class: Cituao\UsuarioBundle\Example

#services:
#  login_listener:
#    class: Cituao\UsuarioBundle\Listener\SecurityListener
#    scope: container
#    arguments: [@security.context, @router]
#    tags:
#3           - { name: kernel.event_listener, event: security.interactive_login }
#           - { name: kernel.event_listener, event: kernel.response }
