parameters:
#    cituao_usuario.example.class: Cituao\UsuarioBundle\Example

services:
#    cituao_usuario.example:
#        class: %cituao_usuario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
  access_listener:
    class: Cituao\UsuarioBundle\Listener\SecurityListener
    scope: request
    arguments: [  @router, @security.context, @event_dispatcher ]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
	  
</service>