cituao_practicante_homepage:
    path:  /practicante
    defaults: { _controller: CituaoPracticanteBundle:Default:index }

cituao_practicante_mihojadevida:
    path:  /practicante/mihojadevida
    defaults: { _controller: CituaoPracticanteBundle:Default:hojadevida }

cituao_practicante_cronograma:
    path:  /practicante/cronograma
    defaults: { _controller: CituaoPracticanteBundle:Default:cronograma }

cituao_practicante_registrar_asesoria:
    path:  /practicante/registrarasesoria/practicante={id}&asesoria={numase}
    defaults: { _controller: CituaoPracticanteBundle:Default:registrarAsesoria }

cituao_practicante_registrar_cualicuanti:
    path:  /practicante/registrarcualicuanti/practicante={id}&cualicuanti={numcua}
    defaults: { _controller: CituaoPracticanteBundle:Default:registrarCualicuanti }