Cituao\PracticanteBundle\Entity\Docpdf:
    properties:
        file:
            - File:
                maxSize: 8192k
                mimeTypes: [application/pdf, application/x-pdf]
                mimeTypesMessage: Por favor suba un PDF!
                uploadErrorMessage: El archivo no puede ser cargado!
