cituao_coord_homepage:
    pattern:  /coordinador
    defaults: { _controller: CituaoCoordBundle:Default:index }

cituao_coord_practicantes:
    pattern:  /coordinador/practicantes
    defaults: { _controller: CituaoCoordBundle:Default:practicantes }

cituao_coord_practicante:
    pattern:  /coordinador/practicante/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:practicante }

cituao_coord_cronograma:
    pattern:  /coordinador/cronograma/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:cronograma }

cituao_coord_cargar_estudiantes:
    pattern:  /coordinador/cargarestudiantes
    defaults: { _controller: CituaoCoordBundle:Default:upload }

cituao_coord_asesores:
    pattern:  /coordinador/asesores
    defaults: { _controller: CituaoCoordBundle:Default:asesores }

