cituao_coord_homepage:
    pattern:  /coordinador
    defaults: { _controller: CituaoCoordBundle:Default:index }

cituao_coord_practicantes:
    pattern:  /coordinador/practicantes
    defaults: { _controller: CituaoCoordBundle:Default:practicantes }

cituao_coord_practicante:
    pattern:  /coordinador/practicante/{codigo}
    defaults: { _controller: CituaoCoordBundle:Default:practicante }
