cituao_coord_homepage:
    pattern:  /coordinador
    defaults: { _controller: CituaoCoordBundle:Default:index }

cituao_coord_practicantes:
    pattern:  /coordinador/practicantes
    defaults: { _controller: CituaoCoordBundle:Default:practicantes }

cituao_coord_practicante:
    pattern:  /coordinador/practicante/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:practicante }

cituao_coord_registrar_practicante:
    pattern:  /coordinador/registrarpracticante
    defaults: { _controller: CituaoCoordBundle:Default:registrarPracticante }

cituao_coord_cronograma:
    pattern:  /coordinador/cronograma/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:cronograma }

cituao_coord_cargar_estudiantes:
    pattern:  /coordinador/cargarestudiantes
    defaults: { _controller: CituaoCoordBundle:Default:upload }

cituao_coord_asesores:
    pattern:  /coordinador/asesores
    defaults: { _controller: CituaoCoordBundle:Default:asesores }

cituao_coord_registrarexterno:
    pattern:  /coordinador/registrarexterno
    defaults: { _controller: CituaoCoordBundle:Default:registrarexterno }

cituao_coord_externo:
    pattern:  /coordinador/externo/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:externo }

cituao_coord_academicos:
    pattern:  /coordinador/academicos
    defaults: { _controller: CituaoCoordBundle:Default:academicos }

cituao_coord_registraracademico:
    pattern:  /coordinador/registraracademico
    defaults: { _controller: CituaoCoordBundle:Default:registraracademico }

cituao_coord_academico:
    pattern:  /coordinador/academico/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:academico }
