cituao_coord_homepage:
    pattern:  /coordinador
    defaults: { _controller: CituaoCoordBundle:Default:index }

cituao_coord_practicantes:
    pattern:  /coordinador/practicantes
    defaults: { _controller: CituaoCoordBundle:Default:practicantes }

cituao_coord_practicantes_asesor:
    path:  /coordinador/practicantes-asesor={ci}
    defaults: { _controller: CituaoCoordBundle:Default:practicantesAsesor }

cituao_coord_practicante:
    pattern:  /coordinador/practicante/{codigo}
    defaults: { _controller: CituaoCoordBundle:Default:practicante }

cituao_coord_registrar_practicante:
    pattern:  /coordinador/registrarpracticante
    defaults: { _controller: CituaoCoordBundle:Default:registrarPracticante }

cituao_coord_cronograma:
    pattern:  /coordinador/cronograma/{codigo}
    defaults: { _controller: CituaoCoordBundle:Default:cronograma }

cituao_coord_cronograma_eliminar:
    pattern:  /coordinador/cronograma-eliminar/{id}
    defaults: { _controller: CituaoCoordBundle:Default:cronogramaEliminar }

cituao_coord_cargar_estudiantes:
    pattern:  /coordinador/cargarestudiantes
    defaults: { _controller: CituaoCoordBundle:Default:upload }

cituao_coord_asesores:
    pattern:  /coordinador/asesores
    defaults: { _controller: CituaoCoordBundle:Default:asesores }

cituao_coord_registrarexterno:
    pattern:  /coordinador/registrarexterno
    defaults: { _controller: CituaoCoordBundle:Default:registrarexterno }

cituao_coord_externo:
    pattern:  /coordinador/externo/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:externo }

cituao_coord_obtener_externos:
    pattern:  /coordinador/obtenerexternosporcentro
    defaults: { _controller: CituaoCoordBundle:Default:obtenerexternosporcentro}	

cituao_coord_academicos:
    pattern:  /coordinador/academicos
    defaults: { _controller: CituaoCoordBundle:Default:academicos }

cituao_coord_registraracademico:
    pattern:  /coordinador/registraracademico
    defaults: { _controller: CituaoCoordBundle:Default:registraracademico }

cituao_coord_academico:
    pattern:  /coordinador/academico/{ci}
    defaults: { _controller: CituaoCoordBundle:Default:academico }

cituao_coord_centros:
    pattern:  /coordinador/centros
    defaults: { _controller: CituaoCoordBundle:Default:centros }

cituao_coord_registrarcentro:
    pattern:  /coordinador/registrarcentro
    defaults: { _controller: CituaoCoordBundle:Default:registrarCentro }

cituao_coord_centro:
    pattern:  /coordinador/centro/{codigo}
    defaults: { _controller: CituaoCoordBundle:Default:centro }

cituao_coord_configuracion:
    pattern:  /coordinador/configuracion
    defaults: { _controller: CituaoCoordBundle:Default:configuracion }

cituao_coord_registrar_coordinador:
    pattern:  /coordinador/registrarcoordinador
    defaults: { _controller: CituaoCoordBundle:Default:registrarcoordinador }

cituao_coord_cronograma_practicante:
    pattern:  /coordinador/vercronograma/practicante={id}
    defaults: { _controller: CituaoCoordBundle:Default:cronogramapracticante }

cituao_coord_consultar_asesoria:
    path:  /coordinador/consultarasesoria/practicante={id}&asesoria={numase}
    defaults: { _controller: CituaoCoordBundle:Default:consultarAsesoria }

cituao_coord_consultar_visitap:
    path:  /coordinador/consultarvisita/practicante={id}
    defaults: { _controller: CituaoCoordBundle:Default:consultarVisitap }

cituao_coord_consultar_evaluacion:
    path:  /coordinador/consultar_evaluacion/practicante={id}&evaluacion={numeva}
    defaults: { _controller: CituaoCoordBundle:Default:consultarEvaluacion }

cituao_coord_consultar_gestion:
    path:  /coordinador/consultar_gestion/practicante={id}&gestion={numges}
    defaults: { _controller: CituaoCoordBundle:Default:consultarGestion }

cituao_coord_consultar_informefinalacademico:
    path:  /coordinador/consultar-informefinal-academico/practicante={id}
    defaults: { _controller: CituaoCoordBundle:Default:consultarInformefinalacademico }

cituao_coord_consultar_acta:
    path:  /coordinador/consultar-acta/practicante={id}
    defaults: { _controller: CituaoCoordBundle:Default:consultarActa }

cituao_coord_consultar_informefinalpracticante:
    path:  /coordinador/consultar-informefinal-practicante/practicante={id}
    defaults: { _controller: CituaoCoordBundle:Default:consultarInformefinalpracticante }

cituao_coord_consultar_practicantes:
    path:  /coordinador/practicantes/periodo={p}&estado={e}
    defaults: { _controller: CituaoCoordBundle:Default:consultarPracticantes }

cituao_coord_practicantes_periodo:
    pattern:  /coordinador/practicantes-por-periodo/{p}
    defaults: { _controller: CituaoCoordBundle:Default:practicantesPeriodo }

cituao_coord_retrasos_practicante:
    pattern:  /coordinador/practicantes-en-retraso
    defaults: { _controller: CituaoCoordBundle:Default:practicantesRetraso }

cituao_coord_email_practicantes:
    pattern:  /coordinador/notificacion-email-practicantes
    defaults: { _controller: CituaoCoordBundle:Default:enviarCorreosPracticantes }

cituao_coord_retrasos_academico:
    pattern:  /coordinador/academicos-en-retraso
    defaults: { _controller: CituaoCoordBundle:Default:academicosRetraso }