cituao_coord_homepage:
    pattern:  /coordinador
    defaults: { _controller: CituaoCoordBundle:Default:index }

cituao_coord_practicantes:
    pattern:  /coordinador/practicantes
    defaults: { _controller: CituaoCoordBundle:Default:practicantes }

cituao_coord_practicante:
    pattern:  /coordinador/practicante/{codigo}
    defaults: { _controller: CituaoCoordBundle:Default:practicante, codigo: '12502219' }

cituao_coord_cronograma:
    pattern:  /coordinador/cronograma/{codigo}
    defaults: { _controller: CituaoCoordBundle:Default:cronograma, codigo: '12502219' }

cituao_coord_cargar_estudiantes:
    pattern:  /coordinador/cargarestudiantes
    defaults: { _controller: CituaoCoordBundle:Default:cargarEstudiantes }

