Cituao\UsuarioBundle\Entity\Programa:
    type: entity
    table: null
    repositoryClass: Cituao\UsuarioBundle\Entity\ProgramaRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '100'
        coordinador:
            type: string
            length: '25'
        email:
            type: string
            length: '50'
    oneToMany:
        practicantes:
            targetEntity: Cituao\CoordBundle\Entity\Practicante
            mappedBy: programa
        centros:
            targetEntity: Cituao\CoordBundle\Entity\Centro
            mappedBy: programa
            orderBy:
                nombre: ASC                
    manyToMany:
        academicos:
            targetEntity: Cituao\AcademicoBundle\Entity\Academico                
            mappedBy: programas

        externos:
            targetEntity: Cituao\ExternoBundle\Entity\Externo                
            mappedBy: programas
            orderBy:
                nombres: ASC
    lifecycleCallbacks: {  }
