Cituao\UsuarioBundle\Entity\Role:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '30'
        role:
            type: string
            length: '20'
    manyToMany:
        users:
            targetEntity: Usuario
            mappedBy: roles
    lifecycleCallbacks: {  }
