Cituao\UsuarioBundle\Entity\Usuario:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: '25'
            unique: true
        salt:
            type: string
            length: '255'
        password:
            type: string
            length: '255'
        is_active:
            type: boolean
    manyToMany:
        roles:
            targetEntity: Role
            inversedBy: users
            joinTable:
              name: usuario_role
              joinColumns:
                usuario_id:
                  referencedColumnName: id
              inverseJoinColumns:
                role_id:
                  referencedColumnName: id

    lifecycleCallbacks: {  }
